### ISSUE TITLE
Issue on GridLauncherV3

### ISSUE THREAD

**Issue by aruvimal** [bonigarcia/webdrivermanager-examples#12]
need to launch the Selenium Hub and Node via direct a Java Program, I saw examples online for launching it via GridLauncherV3 from Selenium. 

(already imported all required library)
import io.github.bonigarcia.wdm.WebDriverManager;

public static void main(String[] args) throws Exception {
	        WebDriverManager.chromedriver().setup();
	        GridLauncherV3.main(new String[] { "-role", "node", "-hub", "http://localhost:4444/grid/register", "-browser",
	                "browserName=chrome", "-port", "5555" });
	    }

But getting below error.

11:29:55.499 INFO [GridLauncherV3.parse] - Selenium server version: 3.141.59, revision: e82be7d358
11:29:55.704 INFO [GridLauncherV3.lambda$buildLaunchers$7] - Launching a Selenium Grid node on port 5555
Exception in thread "main" java.lang.NoClassDefFoundError: javax/servlet/http/HttpServlet
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.openqa.grid.internal.utils.SelfRegisteringRemote.<init>(SelfRegisteringRemote.java:83)
	at org.openqa.grid.internal.utils.SelfRegisteringRemote.<init>(SelfRegisteringRemote.java:72)
	at org.openqa.grid.selenium.GridLauncherV3.lambda$buildLaunchers$7(GridLauncherV3.java:281)
	at org.openqa.grid.selenium.GridLauncherV3.lambda$launch$0(GridLauncherV3.java:86)
	at java.util.Optional.map(Optional.java:215)
	at org.openqa.grid.selenium.GridLauncherV3.launch(GridLauncherV3.java:86)
	at org.openqa.grid.selenium.GridLauncherV3.main(GridLauncherV3.java:70)
	at Demo.StartHub.main(StartHub.java:24)
Caused by: java.lang.ClassNotFoundException: javax.servlet.http.HttpServlet
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)

**Comment by bonigarcia** [comment]
It is solved in this project with the latest patches (there was a problem with the `selenium-api` dependency and the version of Selenium).
