### ISSUE TITLE
ChromeDriver not working

### ISSUE THREAD

**Issue by SchulteMarkus** [bonigarcia/webdrivermanager-examples#2]
For any Chrome-related test of this project, I am getting an exception

    org.openqa.selenium.SessionNotCreatedException: session not created exception: 
    Chrome version must be >= 58.0.3029.0

Steps to reproduce 

    $ git clone git@github.com:bonigarcia/webdrivermanager-examples.git
    $ cd webdrivermanager-examples/
    webdrivermanager-examples $ mvn clean verify

Full exception is (from ChromeTest):

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running io.github.bonigarcia.wdm.test.ChromeTest
[2017-06-12 11:29:22:956] [main] INFO BrowserManager - Reading https://chromedriver.storage.googleapis.com/ to seek [chromedriver]
[2017-06-12 11:29:23:573] [main] INFO BrowserManager - Latest version of [chromedriver] is 2.30
[2017-06-12 11:29:23:580] [main] INFO BrowserManager - Exporting webdriver.chrome.driver as /home/markus-tarent/.m2/repository/webdriver/chromedriver/linux64/2.30/chromedriver
Starting ChromeDriver 2.30.477691 (6ee44a7247c639c0703f291d320bdf05c1531b57) on port 29370
Only local connections are allowed.
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.904 sec <<< FAILURE! - in io.github.bonigarcia.wdm.test.ChromeTest
test(io.github.bonigarcia.wdm.test.ChromeTest)  Time elapsed: 0.59 sec  <<< ERROR!
org.openqa.selenium.SessionNotCreatedException: session not created exception: Chrome version must be >= 58.0.3029.0
  (Driver info: chromedriver=2.30.477691 (6ee44a7247c639c0703f291d320bdf05c1531b57),platform=Linux 4.4.0-79-generic x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 326 milliseconds
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'markus-Aspire-VN7-592G', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-79-generic', java.version: '1.8.0_131'
Driver info: driver.version: ChromeDriver
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:215)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:167)
	at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$new$0(JsonWireProtocolResponse.java:53)
	at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$getResponseFunction$2(JsonWireProtocolResponse.java:91)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$22(ProtocolHandshake.java:365)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:368)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:159)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:637)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:250)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:236)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:137)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:184)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:171)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:124)
	at io.github.bonigarcia.wdm.test.ChromeTest.setupTest(ChromeTest.java:49)
```

**Comment by bonigarcia** [comment]
You need to upgrade Chrome:

> Chrome version must be >= 58.0.3029.0

**Comment by SchulteMarkus** [comment]
But chromedriver is downloaded as part of this manager, or am I missing something?

**Comment by bonigarcia** [comment]
WebDriverManager downloads the latest version of chromedriver by default. The actual browser should be installed beforehand in order to make the test to work. It seems that chromedriver 2.30 require Chrome >= 58.0.3029.0.

**Comment by SchulteMarkus** [comment]
Thanks for the clarification.
