### ISSUE TITLE
java.lang.NoClassDefFoundError: org/apache/hc/core5/http/ClassicHttpRequest with new version

### ISSUE THREAD

**Issue by gregma** [bonigarcia/webdrivermanager-examples#20]
Just upgraded from webdrivermanager 3.8.1 to 4.2.2 in order to pick up the Edge fixes.  However, I'm running into issues.  I had to upgrade several other pieces because I think the new webdrivermanager requires them (commons-io from 2.6 to 2.8.0, new commons-lang3 to 3.11, new httpclient5 to 5.0.1, new jarchivelib to 1.1.0.  

Here is the relevant versions from my POM now:

		<commons-io.version>2.8.0</commons-io.version>
		<commons-lang3.version>3.11</commons-lang3.version>
		<commons-text.version>1.6</commons-text.version>
		<httpclient.version>4.5.12</httpclient.version>
		<httpclient5.version>5.0.1</httpclient5.version>
		<jarchivelib.version>1.1.0</jarchivelib.version>
		<selenium-java.version>3.141.59</selenium-java.version>
		<testng.version>6.14.3</testng.version>
		<webdrivermanager.version>4.2.2</webdrivermanager.version>

The line(s) that are causing this are:

            WebDriverManager.chromedriver().clearResolutionCache().setup();
or any WebDriverManager.edgedriver().setup();

The error I'm now getting is (this occurs trying to :)

java.lang.NoClassDefFoundError: org/apache/hc/core5/http/ClassicHttpRequest

	at framework.DriverFactory.getDriver(DriverFactory.java:257)
	at tests.BaseTest.launchDriver(BaseTest.java:1081)
	at tests.BaseTest.beforeSuite(BaseTest.java:798)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)
Caused by: java.lang.ClassNotFoundException: org.apache.hc.core5.http.ClassicHttpRequest
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 22 more

**Comment by gregma** [comment]
Figured this out, I had to put the core5 into my pom.xml.  There are other issues now though.
