### ISSUE TITLE
Unable to launch chrome or firefox driver

### ISSUE THREAD

**Issue by o-suneel-kumar** [bonigarcia/webdrivermanager-examples#5]
hi ,

I tried launching chrome /FF driver, got exception. Below logs and exception stacktrace.:

SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/C:/Users/skoleti.ORADEV/.m2/repository/org/slf4j/slf4j-simple/1.7.21/slf4j-simple-1.7.21.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/C:/Users/skoleti.ORADEV/.m2/repository/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.SimpleLoggerFactory]
[2017-10-16 09:38:10:013] [main] INFO BrowserManager - Reading https://api.github.com/repos/mozilla/geckodriver/releases to seek [wires, geckodriver]
[2017-10-16 09:38:10:734] [main] INFO BrowserManager - Latest version of [wires, geckodriver] is 0.19.0
[2017-10-16 09:38:10:795] [main] INFO BrowserManager - Exporting webdriver.gecko.driver as C:\Users\skoleti.ORADEV\.m2\repository\webdriver\geckodriver\win64\0.19.0\geckodriver.exe
Exception in thread "main" java.lang.NoClassDefFoundError: org/openqa/selenium/io/CircularOutputStream
	at org.openqa.selenium.firefox.FirefoxBinary.<init>(FirefoxBinary.java:60)
	at org.openqa.selenium.firefox.FirefoxBinary.<init>(FirefoxBinary.java:56)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:120)
	at com.he.executionlayer.ApiProcessor.getDriver(ApiProcessor.java:723)
	at com.he.executionlayer.ApiProcessor.main(ApiProcessor.java:201)
Caused by: java.lang.ClassNotFoundException: org.openqa.selenium.io.CircularOutputStream
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 5 more

**Comment by pinakinc** [comment]
Hi

I get the error below.

I am using Selenium webdriver 3.14 and WebDriverManager 3.0. I get the error below


Exception in thread "main" java.lang.NoClassDefFoundError: io/github/bonigarcia/wdm/WebDriverManager
	at org.packt.utilities.BrowserFactory.main(BrowserFactory.java:12)
Caused by: java.lang.ClassNotFoundException: io.github.bonigarcia.wdm.WebDriverManager
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 1 more

**Comment by HarinathAnnavarapu** [comment]
Can anyone kindly provide the solution for the above-specified exception?

**Comment by swathi-prasad** [comment]
Any update on this issue? I still face it with WebDriverManager  v3.7.0

**Comment by swathi-prasad** [comment]
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 2 more
