### ISSUE TITLE
java.lang.NoClassDefFoundError: io/github/bonigarcia/wdm/WebDriverManager

### ISSUE THREAD

**Issue by suhailsqm** [bonigarcia/webdrivermanager-examples#82]
Hi, I am getting the following error. I am new to Maven and selenium. Some one please help me.

C:\Users\win10\vilcart\vilcart-app>java -cp target\vilcart-app-1.0-SNAPSHOT.jar com.vilcart.app.App
Exception in thread "main" java.lang.NoClassDefFoundError: io/github/bonigarcia/wdm/WebDriverManager
        at com.vilcart.app.App.main(App.java:16)
Caused by: java.lang.ClassNotFoundException: io.github.bonigarcia.wdm.WebDriverManager
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 1 more

package com.vilcart.app;

import io.github.bonigarcia.wdm.WebDriverManager;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

/**
 * Hello world!
 *
 */
public class App 
{
    public static void main( String[] args )
    {
	   WebDriverManager.chromedriver().setup();
           ChromeDriver driver = new ChromeDriver();
	   System.out.println( "Hello World!" );
           driver.quit();
    }
}

My pom.xml file is.

<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>com.vilcart.app</groupId>
  <artifactId>vilcart-app</artifactId>
  <version>1.0-SNAPSHOT</version>

  <name>vilcart-app</name>
  
  <url>http://www.example.com</url>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.source>18</maven.compiler.source>
    <maven.compiler.target>18</maven.compiler.target>
  </properties>

  <dependencies>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.13.2</version>
      
    </dependency>
	
	<dependency>
		<groupId>org.testng</groupId>
		<artifactId>testng</artifactId>
		<version>7.6.0</version>
		<scope>compile</scope>
	</dependency>

    <dependency>
      <groupId>org.seleniumhq.selenium</groupId>
      <artifactId>selenium-java</artifactId>
      <version>4.2.2</version>
    </dependency>
    <dependency>
        <groupId>io.github.bonigarcia</groupId>
        <artifactId>webdrivermanager</artifactId>
        <version>5.2.0</version>
    </dependency> 
	
    <dependency>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-shade-plugin</artifactId>
        <version>3.3.0</version>
    </dependency>
	
	<dependency>
		<groupId>org.seleniumhq.selenium</groupId>
		<artifactId>selenium-api</artifactId>
		<version>4.2.2</version>
	</dependency>

	
	<dependency>
		<groupId>org.seleniumhq.selenium</groupId>
		<artifactId>selenium-chrome-driver</artifactId>
		<version>4.2.2</version>
	</dependency>
	
	<dependency>
		<groupId>org.apache.maven.plugins</groupId>
		<artifactId>maven-surefire-plugin</artifactId>
		<version>3.0.0-M7</version>
	</dependency>
	
	<dependency>
		<groupId>org.apache.maven.plugins</groupId>
		<artifactId>maven-compiler-plugin</artifactId>
		<version>3.10.1</version>
	</dependency>

  </dependencies>

  <build>
    <pluginManagement>
      <plugins>
        
        <plugin>
          <artifactId>maven-clean-plugin</artifactId>
          <version>3.2.0</version>
        </plugin>
        
        <plugin>
          <artifactId>maven-resources-plugin</artifactId>
          <version>3.2.0</version>
        </plugin>
        <plugin>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>3.8.0</version>
        </plugin>
        <plugin>
          <artifactId>maven-surefire-plugin</artifactId>
          <version>3.0.0-M7</version>
        </plugin>
        
		<plugin>
			<groupId>org.apache.maven.plugins</groupId>
			<artifactId>maven-shade-plugin</artifactId>
			<version>3.3.0</version>
			 <executions>
			   <execution>
					<phase>package</phase>
					<goals>
					   <goal>shade</goal>
					</goals>
					<configuration>
						 <transformers>
							<transformer 
		implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
								<mainClass>com.vilcart.app.App</mainClass>
							</transformer>
						 </transformers>
					 </configuration>
			   </execution>
			</executions> 
		</plugin>
        <plugin>
          <artifactId>maven-install-plugin</artifactId>
          <version>3.0.0-M1</version>
        </plugin>
        <plugin>
          <artifactId>maven-deploy-plugin</artifactId>
          <version>3.0.0-M2</version>
        </plugin>
        
        <plugin>
          <artifactId>maven-site-plugin</artifactId>
          <version>4.0.0-M1</version>
        </plugin>
        <plugin>
          <artifactId>maven-project-info-reports-plugin</artifactId>
          <version>3.3.0</version>
        </plugin>
		<plugin>
		  <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-source-plugin</artifactId>
          <version>3.2.1</version>
		
      </plugin>
      </plugins>
    </pluginManagement>
  </build>
</project>

**Comment by suhailsqm** [comment]
My classpath is this 
C:\Users\win10\vilcart\vilcart-app>echo %CLASSPATH%
C:\Users\win10\.m2\repository;.;

**Comment by suhailsqm** [comment]
It works in eclipse but it doesn't work in WIndows command line.
